// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUPMmB9tyitBXjjJvQxMCICQqoWahz3Hc',
    appId: '1:643877734928:web:8c0756e9950fe541405895',
    messagingSenderId: '643877734928',
    projectId: 'prova-flutter-gdp',
    authDomain: 'prova-flutter-gdp.firebaseapp.com',
    storageBucket: 'prova-flutter-gdp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFDfP_4bIUWqfYJLYtYgcrynJNnqHtKzE',
    appId: '1:643877734928:android:a5be0a0c359f9bee405895',
    messagingSenderId: '643877734928',
    projectId: 'prova-flutter-gdp',
    storageBucket: 'prova-flutter-gdp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw-gmgvr_rkh7TVxv6v8Z3tGMk-aKSaS4',
    appId: '1:643877734928:ios:6c1fee1d021fa606405895',
    messagingSenderId: '643877734928',
    projectId: 'prova-flutter-gdp',
    storageBucket: 'prova-flutter-gdp.firebasestorage.app',
    iosBundleId: 'com.example.keyGenApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw-gmgvr_rkh7TVxv6v8Z3tGMk-aKSaS4',
    appId: '1:643877734928:ios:6c1fee1d021fa606405895',
    messagingSenderId: '643877734928',
    projectId: 'prova-flutter-gdp',
    storageBucket: 'prova-flutter-gdp.firebasestorage.app',
    iosBundleId: 'com.example.keyGenApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUPMmB9tyitBXjjJvQxMCICQqoWahz3Hc',
    appId: '1:643877734928:web:38ae0dc42f37d129405895',
    messagingSenderId: '643877734928',
    projectId: 'prova-flutter-gdp',
    authDomain: 'prova-flutter-gdp.firebaseapp.com',
    storageBucket: 'prova-flutter-gdp.firebasestorage.app',
  );
}
